### ISSUE TITLE
Invalid generation when package is camel case

### ISSUE THREAD

**Issue by deogo** [danielgtaylor/python-betterproto#514]
```toml
grpcio = "1.54.0"
grpcio-tools = "^1.52.0"
betterproto = {version = "2.0.0b6", extras = ["compiler"]}
```

Compiling proto like this

```proto
syntax = "proto3";

package helloThere;

// Greeting represents a message you can tell a user.
message Greeting {
  string message = 1;
  Model model = 2;
}

message Model {
    double value = 1;
}
```

creates python file
```python
from dataclasses import dataclass

import betterproto

from .. import HelloThereModel as _HelloThereModel__


@dataclass(eq=False, repr=False)
class Greeting(betterproto.Message):
    """Greeting represents a message you can tell a user."""

    message: str = betterproto.string_field(1)
    model: "_HelloThereModel__" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class Model(betterproto.Message):
    value: float = betterproto.double_field(1)

```

Which does not work due to some relative imports
If you fix package name `helloThere` -> `hello_there` it work ok
