### ISSUE TITLE
feature: support beta versions in the buf remote plugin

### ISSUE THREAD

**Issue by redbmk** [danielgtaylor/python-betterproto#516]
Using `buf` to generate protos is really nice especially with remote plugins where you don't need to install as many dev dependencies locally. It looks like there's a community-supported remote plugin for `betterproto`, but it currently only supports v1.2.5: https://buf.build/community/danielgtaylor-betterproto

It would be nice to be able to use the same plugin to build off the beta versions before they're released.

Currently to generate with v1.2.5, this is all that's required:

**buf.gen.yaml**
```yaml
version: v1
managed:
  enabled: true
plugins:
  - plugin: buf.build/community/danielgtaylor-betterproto
    out: app/proto
```

**buf.work.yaml**
```yaml
version: v1
directories:
  - proto/source/folder
```

and then run `buf generate` (e.g. with `npx @bufbuild/buf generate`). If the beta versions were hosted, we would be able to just update the `buf.gen.yaml` to look more like:

```yaml
version: v1
managed:
  enabled: true
plugins:
  - plugin: buf.build/community/danielgtaylor-betterproto:v2.0.0-beta6
    out: app/proto
    opt:
      - pydantic_dataclasses
```
