### ISSUE TITLE
How to enable @dataclass(eq=True, repr=True)?

### ISSUE THREAD

**Issue by heimalne** [danielgtaylor/python-betterproto#527]
We needed to upgrade from 1.2.5 to the newest beta 2.0.0b6 and noticed that messages now have
```
@dataclass(eq=False, repr=False)
```
by default. Is there a way to generate classes with eq and repr being True? I couldn't find anything in the docs.

**Comment by Gobot1234** [comment]
Regenerate the files using the compiler

**Comment by heimalne** [comment]
I think that's what we do (analogous to the betterproto docs):
```bash
python -m grpc_tools.protoc --proto_path=../protobuf  --python_betterproto_out=. $(find ../protobuf -name '*.proto')
```
Or are there special variants?

Our dependencies are as follows:
```toml
[tool.poetry.dependencies]
python       = "^3.9"
betterproto  = { version = "2.0.0b6"}
grpclib      = { version = "0.4.3"}
grpcio-tools = { version = "1.56.0"}
```
